version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: yWebSite_mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sample
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: yWebSite_phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
